version: "3.9"
services:
  db:
    container_name: local_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ayaz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
