version: '3.9'
services:
  app:
    container_name: next_app_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      # Helps Docker detect file changes reliably
      CHOKIDAR_USEPOLLING: "true"

  db:
    container_name: local_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ayaz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
